### ISSUE TITLE
Not working getting the error.

### ISSUE THREAD

**Issue by anonymous40404** [tuhin1729/Bot#3]
Trying From 206.127.88.18:80
Traceback (most recent call last):
  File "lol.py", line 70, in <module>
    req(purl,target,timeout,stay)
  File "lol.py", line 59, in req
    driver.close()
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by solbin2255** [comment]
same error

**Comment by Ali83128** [comment]
Hey Don't Use Sudo when running the Bot.
